### PR TITLE
Made a Chrome Version

### PR DESCRIPTION
**Pull request by gsp8181**
Go into dev mode in chrome://extensions/ and load as an unpacked extension to test for the meantime
You can pack it up using a private key and submit to the chrome web store

### CODE REVIEW

**Comment by dutts** [comment]
Argh, thanks so much for this but I've just knocked up a Chrome version myself on my train home but couldn't push to github. Interested to see what you've done though as I've not got much experience with addons at all.
Again, sorry! Thanks for the contribution.

**Comment by gsp8181** [comment]
No problem! It's pretty easy to convert firefox addons to chrome that simply use JS, just have to change a few browser specific methods. You could eventually have something like if(chrome.extension == undefined) then firefox image link else chrome image link

Also i'd remove the .pem file and regenerate your private key as you have inadvertently uploaded it, chrome attaches it when you build it

**Comment by dutts** [comment]
Again, sorry about that. Really appreciate the help anyway. If you ever want to contribute again to NomOrVom please check out the unassigned Issues in the list. If it's assigned it means I'm actively developing/testing but everything else is free to grab.

Ah I knew I'd do something stupid. I'm confused though as the submission process wants a zip of my addon folder, not my crx file, when does it ever use the key?

**Comment by dutts** [comment]
Ah https://developer.chrome.com/extensions/packaging explains it, I'm publishing via the Developer Dashboard so don't need to package and sign. Replaced and deleted the key anyway just to be on the safe side. Thanks for pointing it out =)

**Comment by gsp8181** [comment]
The crx is used to authenticate the build is from you and chrome will look
if the signature is different when updating the extension.

**Pull request closed without merging**
